name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: Check out code 
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies and package
        run: |
          python -m pip install --upgrade pip build
          pip install .
          pip install .[dev]
      - name: Cache APT Packages (Linux)
        uses: awalsh128/cache-apt-pkgs-action@v1.4.3
        with:
          packages: bedtools
          version: 1.0
      - name: Lint
        run: flake8 .
      - name: Type checking
        run: mypy . --exclude setup.py
      - name: Run tests
        run: |
          coverage run -m pytest
          coverage xml
      - name: Check module
        run: python -m arithmetic.addition
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml-${{ matrix.python-version }}
          path: coverage.xml
  user-fail:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code 
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install dependencies and package
        run: |  # Explicitly install numpy < 2
          python -m pip install --upgrade pip build
          pip install .
          pip install .[dev]
          pip install numpy==1.23
      - name: Run tests
        run: coverage run -m pytest tests/test_arithmetic.py
      - name: Check module
        run: python -m arithmetic.addition
